## YAML Template.
---
input_count: 10
out_count: 10
out_magnification: 10
out_exchange: 9
item:
    input: "minecraft:emerald"
    out_item: "minecraft;emerald"
    out_block: "minecraft;emerald_block"