## YAML Template.
---
name: Minecraft_Slot_Plugin
version: 0.1
description: slot plugin.
author: Mamireimu
website: mamireimuserver.com
#---
main: com.mamireimuserver.minecraft.slot.plugin.Main
#---
commands:
    slot_play:
        description: test command.
        permission: slot.play
permissions:
    slot.*:
        description: all Permission
        children:
            slot.play: true
    slot.play:
        description: スロットをプレイする
        default: true
    slot.set:
           default: op