## YAML Template.
---
name: Minecraft_Slot_Plugin
version: 0.1
description: slot plugin.
author: Mamireimu&Crousand
website: mamireimuserver.com
#---
main: com.mamireimuserver.minecraft.slot.plugin.Main
#---
commands:
   slot:
      description: no description
      permission: slot.default
   slotsetting:
      description: no description
      permission: slot.op
permissions:
   slot.op:
        description: /help no komando no setumei
        default: op
   slot.default:
        description: /help no komando no setumei
        default: default